config/routes.rb
Myrottenpotatoes::Application.routes.draw do

	get '/movies/search_tmdb', :controller => 'movies', :action => 'search_tmdb'
	post '/movies/createfromtmdb', :controller => 'movies', :action => 'create_from_tmdb'

	resources :movies do
		resources :reviews
	end

	root :to => redirect('/movies')

	# fb authentication
	devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

	before_action :require_login, :except => [:index, :show, :search_tmdb]

	def require_login
		unless @current_user
			flash[:warning] = "You have to login first!!!"
			redirect_to movies_path
		end
	end

	########## HOME PAGE ##########
	def index
		@all_movies = Movie.all
		@movies = @all_movies.order('title')
	end

	########## SHOW DETAILS PAGE ##########
	def show
		begin
			# find movie by id
			id = params[:id]
			@movie = Movie.find(id)
			# show up app/views/movies/show.html.haml
			@review = Review.find_by_movie_id(id)
		rescue ActiveRecord::RecordNotFound
			flash[:warning] = "Movie is not found."
			redirect_to movies_path
		end
	end

	# information for creating and updating movie's details
	def movie_info
		params.require(:movie).permit(:title, :rating, :release_date, :description)
	end

	########## CREATE PAGE ##########
	def new
		@movie = Movie.new
	end

	def create 
		# create movie by movie's info
		@movie = Movie.new(movie_info)
		if @movie.save
			# if creation is successful, show up 'successful' message
			flash[:notice] = "#{@movie.title} was successfully created."
			# if creation is successful, redirect to home page
			redirect_to new_movie_review_path(@movie)
		else
			# if user doesn't type anything
			render 'new'
		end
	end

	########## EDIT (UPDATE) PAGE ##########
	def edit
		# find movie by id
		id = params[:id]
		@movie = Movie.find(id)
	end

	def update
		# find movie by id
		id = params[:id]
		@movie = Movie.find(id)
		# update movie's details
		if @movie.update_attributes(movie_info)
			# if updation is successful, show up successful message
			flash[:notice] = "#{@movie.title} was successfully updated."
			# if updation is successful, redirect to show up movie's details
			redirect_to @movie
		else
			# if user doesn't type anthing
			render 'edit'
		end
	end

	########## DELETE MENU ##########
	def destroy 
		# find movie by id
		id = params[:id]
		@movie = Movie.find(id)
		# delete movie
		@movie.destroy
		# if movie is deleted, show up successful message
		flash[:notice] = "#{@movie.title} deleted."
		# if movie is deleted, redirect to all lists of movies
		redirect_to movies_path
	end

	def search_tmdb
		@search_tmdb = params[:search_tmdb]
		if @search_tmdb == ""
			flash[:warning] = "You cannot blank"
			redirect_to movies_path
		else 
			@movies = Movie.find_in_tmdb(@search_tmdb)
			if @movies != []
				render 'tmdb'
			else
				flash[:warning] = "Sorry, No match for '#{params[:search_tmdb]}'"
				redirect_to movies_path
			end 
		end
	end

	def create_from_tmdb
		movie_id = params[:tmdb_id]
		m = Movie.get_from_tmdb(movie_id)
		@movie = Movie.new({
						:title => m["title"], 
						:rating => "",    
						:release_date => m["release_date"], 
						:description => m["overview"]
		})
		if @movie.save
			flash[:notice] = "'#{@movie.title}' was successfully created."
			redirect_to new_movie_review_path(@movie)
		end
	end

end

app/views/movies/_login.html.haml
#login
	- if @current_user
		%p.welcom
			Welcome, #{@current_user[:name]}!
		%p.logout
			= link_to "Log Out", destroy_user_session_path, method: :delete
	- else
		%p.login
			= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path, method: :post

app/views/movies/_movie_form.html.haml
- unless @movie.errors.empty?
  #warning
    Errors prevented this movie from being #{controller.action_name}d:
    %ul
      - @movie.errors.full_messages.each do |error|
        %li= error

= label :movie, :title, 'Title'
= text_field :movie, 'title'

= label :movie, :rating, 'Rating'
= select :movie, :rating, ['G','PG','PG-13','R','NC-17']
 
= label :movie, :release_date, 'Released On'
= date_select :movie, :release_date, start_year: 1930

= label :movie, :description, 'Description'
= text_area :movie, :description

app/views/movies/edit.html.haml
%h2 Edit Movie

= form_tag movie_path(@movie), :method => :put do

  = render :partial => 'movie_form'

  %br
  = submit_tag 'Edit Info'
  = link_to 'Cancel', movie_path(@movie)

app/views/movies/index.html.haml
%h1 Search TMDB for a movie

= form_tag movies_search_tmdb_path, :method => :get do
	%label Search Terms
	= text_field_tag 'search_tmdb'
	= submit_tag 'Search TMDb'


%h1 All Movies

%table#movies
	%thead
		%tr
			%th NO.
			%th Movie Title
			%th Rating
			%th Release Date
			%th More Info
	%tbody
		- @movies.each_with_index do |movie, index|
			%tr
				%td= index+1
				%td= movie.title 
				%td= movie.rating
				%td= movie.release_date.strftime('%d-%b-%Y')
				%td= link_to "More about #{movie.title}", movie_path(movie)

= link_to 'Add new movie', new_movie_path

app/views/movies/new.html.haml
%h2 Create New Movie

= form_tag movies_path, :method => :post do

  = render :partial => 'movie_form'

  %br
  = submit_tag 'Save Changes'
  = link_to 'Cancel', movies_path

app/views/movies/show.html.haml
%h2 Details about #{@movie.title}

%ul#details
  %li
    Rating:
    = @movie.rating
  %li
    Released on:
    = @movie.release_date.strftime("%d-%b-%Y")

%h3 Description:

%p#description= @movie.description

%br
= link_to 'Edit Info', edit_movie_path(@movie)
%br
= link_to 'Delete', movie_path(@movie), :method => :delete
%br
= link_to 'Back to movie list', movies_path
%br
= link_to 'Show up All Reviews', movie_reviews_path(@movie)
%br

= link_to 'Show up Your Review', movie_review_path(@movie, @review) if not @review.nil?

app/views/movies/tmdb.html.haml
%h1 TMDB search for "#{@search_tmdb}"

%div.tmdb-container

	- @movies.each do |tmdb_mv|
		%div.tmdb-card
			%div.tmdb-poster
				%img.tmdb-poster{:src => 'https://image.tmdb.org/t/p/w300' + tmdb_mv.poster_path.to_s}
			%div.tmdb-detail
				%p.tmdb-title
					= tmdb_mv.title
				%p.tmdb-rl-date
					= tmdb_mv.release_date
				%p.tmdb-description
					= tmdb_mv.overview
				= form_tag movies_createfromtmdb_path, :method => :post do
					%p.tmdb-add-in-db
						%input{:type=>"hidden",:name=>'tmdb_id', :value=>tmdb_mv.id ,}
						= submit_tag 'Add this movie'